### ISSUE TITLE
support target selection by SNI

### ISSUE THREAD

**Issue by cfal** [cfal/tobaru#8]

**Comment by cfal** [comment]
this is now supported.

**Comment by subashsn** [comment]
Hi, does it do transparent TLS pass-through or it decrypts the traffic and sends again. Thanks?

**Comment by cfal** [comment]
if you're using SNI detection, then tobaru is doing the TLS accept. if your endpoint is a TLS server, then tobaru would be doing the TLS connect.

if you want transparent TLS pass-through, you can do that without SNI or ALPN detection.

**Comment by subashsn** [comment]
Thank you for responding! 

My use case is:
- [ ] Listen on 443
- [ ] Based on SNI, forward to different destinations
  - abc.example.com ->  10.10.10.1:443 (Running HTTPS server with valid certificate)
  - xyz.example2.com -> 10.11.11.10:443  (Running HTTPS server with valid certificate)
- [ ] The above should be done without decrypting the traffic at the server side 
  - No TLS certificate(s) should be there on server

Similar to this tool https://github.com/dlundquist/sniproxy

I read through the examples in the readme, but couldn't find a way to do this. All examples involving TLS needed a certificate and key. 
I really wanted something in rust to do this. I wanted something built in Rust
